//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate Fluent Mapping template.
// Code is generated on: 21/01/2012 10:48:48 p.m.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using FluentNHibernate.Mapping;
using FluentNHibernate.MappingModel.Collections;

namespace SicoWeb.Dominio.Core.Entidades.Mantenimientos
{
    public class EntiMunicipioMap : SubclassMap<EntiMunicipio>
    {
        public EntiMunicipioMap()
        {
              LazyLoad();
              References(x => x.EntiDepartamentos)
                .Class<EntiDepartamentos>()
                .Access.Property()
                .Cascade.SaveUpdate()
                .LazyLoad()
                .Columns("IdMantenimientos");
        }
    }

}
