//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 21/01/2012 10:48:47 p.m.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace SicoWeb.Dominio.Core.Entidades.Mantenimientos
{

    /// <summary>
    /// There are no comments for SicoWeb.Dominio.Core.Entidades.Mantenimientos.Mantenimientos in the schema.
    /// </summary>
    public partial class Mantenimientos {

        private int _Id;

        private string _Descripcion;

        private bool _Habilitado;

        private int _Usu;

        private System.DateTime _Fmodif;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();
        
        #endregion

        public Mantenimientos()
        {
            OnCreated();
        }

    
    /// <summary>
    /// There are no comments for Id in the schema.
    /// </summary>
        public virtual int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }

    
    /// <summary>
    /// There are no comments for Descripcion in the schema.
    /// </summary>
        public virtual string Descripcion
        {
            get
            {
                return this._Descripcion;
            }
            set
            {
                this._Descripcion = value;
            }
        }

    
    /// <summary>
    /// There are no comments for Habilitado in the schema.
    /// </summary>
        public virtual bool Habilitado
        {
            get
            {
                return this._Habilitado;
            }
            set
            {
                this._Habilitado = value;
            }
        }

    
    /// <summary>
    /// There are no comments for Usu in the schema.
    /// </summary>
        public virtual int Usu
        {
            get
            {
                return this._Usu;
            }
            set
            {
                this._Usu = value;
            }
        }

    
    /// <summary>
    /// There are no comments for Fmodif in the schema.
    /// </summary>
        public virtual System.DateTime Fmodif
        {
            get
            {
                return this._Fmodif;
            }
            set
            {
                this._Fmodif = value;
            }
        }
    }

}
