//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate Fluent Mapping template.
// Code is generated on: 05/03/2012 11:35:54 p.m.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using FluentNHibernate.Mapping;
using FluentNHibernate.MappingModel.Collections;

namespace SicoWeb.Dominio.Core.Entidades.Mantenimientos
{
    public class EntiTiposfacturasMap : SubclassMap<EntiTiposfacturas>
    {
        public EntiTiposfacturasMap()
        {
              LazyLoad();
        }
    }

}
