//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 05/03/2012 11:35:52 p.m.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace SicoWeb.Dominio.Core.Entidades.Mantenimientos
{

    /// <summary>
    /// There are no comments for SicoWeb.Dominio.Core.Entidades.Mantenimientos.EntiMunicipio in the schema.
    /// </summary>
    public partial class EntiMunicipio : Mantenimientos {

        private EntiDepartamentos _EntiDepartamentos;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();
        
        #endregion

        public EntiMunicipio()
        {
            OnCreated();
        }

        public virtual EntiDepartamentos EntiDepartamentos
        {
            get
            {
                return this._EntiDepartamentos;
            }
            set
            {
                this._EntiDepartamentos = value;
            }
        }
    }

}
