//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 21/01/2012 10:48:47 p.m.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace SicoWeb.Dominio.Core.Entidades.Mantenimientos
{

    /// <summary>
    /// There are no comments for SicoWeb.Dominio.Core.Entidades.Mantenimientos.EntiMarcas in the schema.
    /// </summary>
    public partial class EntiMarcas : Mantenimientos {

        private IList<EntiModelos> _EntiModelos;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();
        
        #endregion

        public EntiMarcas()
        {
            this._EntiModelos = new List<EntiModelos>();
            OnCreated();
        }

        public virtual IList<EntiModelos> EntiModelos
        {
            get
            {
                return this._EntiModelos;
            }
            set
            {
                this._EntiModelos = value;
            }
        }
    }

}
