'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.4952
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.ComponentModel
Imports CrystalDecisions.CrystalReports.Engine
Imports CrystalDecisions.Shared
Imports CrystalDecisions.ReportSource


Public Class crResumenCierre
    Inherits ReportClass

    Public Sub New()
        MyBase.New
    End Sub

    Public Overrides Property ResourceName() As String
        Get
            Return "crResumenCierre.rpt"
        End Get
        Set
            'Do nothing
        End Set
    End Property

    Public Overrides Property NewGenerator() As Boolean
        Get
            Return true
        End Get
        Set
            'Do nothing
        End Set
    End Property

    Public Overrides Property FullResourceName() As String
        Get
            Return "SICO.crResumenCierre.rpt"
        End Get
        Set
            'Do nothing
        End Set
    End Property

    <Browsable (false), _
        DesignerSerializationVisibilityAttribute (DesignerSerializationVisibility.Hidden)> _
    Public ReadOnly Property Section1() As Section
        Get
            Return Me.ReportDefinition.Sections (0)
        End Get
    End Property

    <Browsable (false), _
        DesignerSerializationVisibilityAttribute (DesignerSerializationVisibility.Hidden)> _
    Public ReadOnly Property Section2() As Section
        Get
            Return Me.ReportDefinition.Sections (1)
        End Get
    End Property

    <Browsable (false), _
        DesignerSerializationVisibilityAttribute (DesignerSerializationVisibility.Hidden)> _
    Public ReadOnly Property PageHeaderSection1() As Section
        Get
            Return Me.ReportDefinition.Sections (2)
        End Get
    End Property

    <Browsable (false), _
        DesignerSerializationVisibilityAttribute (DesignerSerializationVisibility.Hidden)> _
    Public ReadOnly Property PageHeaderSection2() As Section
        Get
            Return Me.ReportDefinition.Sections (3)
        End Get
    End Property

    <Browsable (false), _
        DesignerSerializationVisibilityAttribute (DesignerSerializationVisibility.Hidden)> _
    Public ReadOnly Property Section3() As Section
        Get
            Return Me.ReportDefinition.Sections (4)
        End Get
    End Property

    <Browsable (false), _
        DesignerSerializationVisibilityAttribute (DesignerSerializationVisibility.Hidden)> _
    Public ReadOnly Property DetailSection2() As Section
        Get
            Return Me.ReportDefinition.Sections (5)
        End Get
    End Property

    <Browsable (false), _
        DesignerSerializationVisibilityAttribute (DesignerSerializationVisibility.Hidden)> _
    Public ReadOnly Property DetailSection1() As Section
        Get
            Return Me.ReportDefinition.Sections (6)
        End Get
    End Property

    <Browsable (false), _
        DesignerSerializationVisibilityAttribute (DesignerSerializationVisibility.Hidden)> _
    Public ReadOnly Property DetailSection3() As Section
        Get
            Return Me.ReportDefinition.Sections (7)
        End Get
    End Property

    <Browsable (false), _
        DesignerSerializationVisibilityAttribute (DesignerSerializationVisibility.Hidden)> _
    Public ReadOnly Property Section4() As Section
        Get
            Return Me.ReportDefinition.Sections (8)
        End Get
    End Property

    <Browsable (false), _
        DesignerSerializationVisibilityAttribute (DesignerSerializationVisibility.Hidden)> _
    Public ReadOnly Property ReportFooterSection1() As Section
        Get
            Return Me.ReportDefinition.Sections (9)
        End Get
    End Property

    <Browsable (false), _
        DesignerSerializationVisibilityAttribute (DesignerSerializationVisibility.Hidden)> _
    Public ReadOnly Property Section5() As Section
        Get
            Return Me.ReportDefinition.Sections (10)
        End Get
    End Property

    <Browsable (false), _
        DesignerSerializationVisibilityAttribute (DesignerSerializationVisibility.Hidden)> _
    Public ReadOnly Property Parameter_crListaDetallerpt_defiicion() As IParameterField
        Get
            Return Me.DataDefinition.ParameterFields (0)
        End Get
    End Property

    <Browsable (false), _
        DesignerSerializationVisibilityAttribute (DesignerSerializationVisibility.Hidden)> _
    Public ReadOnly Property Parameter_crListaDetallerpt_idtransacciones() As IParameterField
        Get
            Return Me.DataDefinition.ParameterFields (1)
        End Get
    End Property

    <Browsable (false), _
        DesignerSerializationVisibilityAttribute (DesignerSerializationVisibility.Hidden)> _
    Public ReadOnly Property Parameter_crListaDetallerpt_fecha() As IParameterField
        Get
            Return Me.DataDefinition.ParameterFields (2)
        End Get
    End Property

    <Browsable (false), _
        DesignerSerializationVisibilityAttribute (DesignerSerializationVisibility.Hidden)> _
    Public ReadOnly Property Parameter_crListaDetallerpt_cajero() As IParameterField
        Get
            Return Me.DataDefinition.ParameterFields (3)
        End Get
    End Property

    <Browsable (false), _
        DesignerSerializationVisibilityAttribute (DesignerSerializationVisibility.Hidden)> _
    Public ReadOnly Property Parameter_crListaDetallerpt_idsucursales() As IParameterField
        Get
            Return Me.DataDefinition.ParameterFields (4)
        End Get
    End Property

    <Browsable (false), _
        DesignerSerializationVisibilityAttribute (DesignerSerializationVisibility.Hidden)> _
    Public ReadOnly Property Parameter_crListaDetallerpt_tipo() As IParameterField
        Get
            Return Me.DataDefinition.ParameterFields (5)
        End Get
    End Property

    <Browsable (false), _
        DesignerSerializationVisibilityAttribute (DesignerSerializationVisibility.Hidden)> _
    Public ReadOnly Property Parameter_crListaDetalle01rpt_defiicion() As IParameterField
        Get
            Return Me.DataDefinition.ParameterFields (6)
        End Get
    End Property

    <Browsable (false), _
        DesignerSerializationVisibilityAttribute (DesignerSerializationVisibility.Hidden)> _
    Public ReadOnly Property Parameter_crListaDetalle01rpt_idtransacciones() As IParameterField
        Get
            Return Me.DataDefinition.ParameterFields (7)
        End Get
    End Property

    <Browsable (false), _
        DesignerSerializationVisibilityAttribute (DesignerSerializationVisibility.Hidden)> _
    Public ReadOnly Property Parameter_crListaDetalle01rpt_fecha() As IParameterField
        Get
            Return Me.DataDefinition.ParameterFields (8)
        End Get
    End Property

    <Browsable (false), _
        DesignerSerializationVisibilityAttribute (DesignerSerializationVisibility.Hidden)> _
    Public ReadOnly Property Parameter_crListaDetalle01rpt_cajero() As IParameterField
        Get
            Return Me.DataDefinition.ParameterFields (9)
        End Get
    End Property

    <Browsable (false), _
        DesignerSerializationVisibilityAttribute (DesignerSerializationVisibility.Hidden)> _
    Public ReadOnly Property Parameter_crListaDetalle01rpt_idsucursales() As IParameterField
        Get
            Return Me.DataDefinition.ParameterFields (10)
        End Get
    End Property

    <Browsable (false), _
        DesignerSerializationVisibilityAttribute (DesignerSerializationVisibility.Hidden)> _
    Public ReadOnly Property Parameter_crListaDetalle01rpt_tipo() As IParameterField
        Get
            Return Me.DataDefinition.ParameterFields (11)
        End Get
    End Property
End Class

<ToolboxBitmap (GetType (ExportOptions), "report.bmp")> _
Public Class CachedcrResumenCierre
    Inherits Component
    Implements ICachedReport

    Public Sub New()
        MyBase.New
    End Sub

    <Browsable (false), _
        DesignerSerializationVisibilityAttribute (DesignerSerializationVisibility.Hidden)> _
    Public Overridable Property IsCacheable() As Boolean Implements ICachedReport.IsCacheable
        Get
            Return true
        End Get
        Set
            '
        End Set
    End Property

    <Browsable (false), _
        DesignerSerializationVisibilityAttribute (DesignerSerializationVisibility.Hidden)> _
    Public Overridable Property ShareDBLogonInfo() As Boolean Implements ICachedReport.ShareDBLogonInfo
        Get
            Return false
        End Get
        Set
            '
        End Set
    End Property

    <Browsable (false), _
        DesignerSerializationVisibilityAttribute (DesignerSerializationVisibility.Hidden)> _
    Public Overridable Property CacheTimeOut() As TimeSpan Implements ICachedReport.CacheTimeOut
        Get
            Return CachedReportConstants.DEFAULT_TIMEOUT
        End Get
        Set
            '
        End Set
    End Property

    Public Overridable Function CreateReport() As ReportDocument Implements ICachedReport.CreateReport
        Dim rpt As crResumenCierre = New crResumenCierre
        rpt.Site = Me.Site
        Return rpt
    End Function

    Public Overridable Function GetCustomizedCacheKey (ByVal request As RequestContext) As String _
        Implements ICachedReport.GetCustomizedCacheKey
        Dim key As [String] = Nothing
        '// The following is the code used to generate the default
        '// cache key for caching report jobs in the ASP.NET Cache.
        '// Feel free to modify this code to suit your needs.
        '// Returning key == null causes the default cache key to
        '// be generated.
        '
        'key = RequestContext.BuildCompleteCacheKey(
        '    request,
        '    null,       // sReportFilename
        '    this.GetType(),
        '    this.ShareDBLogonInfo );
        Return key
    End Function
End Class
