//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 04/02/2012 09:46:00 p.m.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;

namespace SicoWeb.Dominio.Core.Entidades.Errores
{

    /// <summary>
    /// There are no comments for SicoWeb.Dominio.Core.Entidades.Errores.EntiErrores in the schema.
    /// </summary>
    public partial class EntiErrores : IEntiBase {

        private int _Id;

        private string _Descripcion;
    
        #region Extensibility Method Definitions
        
        partial void OnCreated();
        
        #endregion

        public EntiErrores()
        {
            OnCreated();
        }

    
    /// <summary>
    /// There are no comments for Id in the schema.
    /// </summary>
        public virtual int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this._Id = value;
            }
        }

    
    /// <summary>
    /// There are no comments for Descripcion in the schema.
    /// </summary>
        public virtual string Descripcion
        {
            get
            {
                return this._Descripcion;
            }
            set
            {
                this._Descripcion = value;
            }
        }
    }

}
